// This configuration will be used in next.config.mjs
export const routeConfig = {
  // Enable dynamic rendering for all routes by default
  dynamicParams: true,
  // Revalidate content every hour by default (or set to false for static)
  revalidate: 3600,
}

// Export route segment config for use in page.tsx files
export const routeSegmentConfig = {
  // Allow dynamic params that aren't generated by generateStaticParams
  dynamicParams: true,
  // Revalidate content every hour (or set to false for static)
  revalidate: 3600,
}
